"use client";

import { useEffect, useState } from "react";
import type { PortalProject } from "@/lib/portal";
import { portalUploadUrl } from "@/lib/portal";

const statusLabels:Record<string,string>={planning:"Planung",waiting_content:"Warten auf Inhalte",design:"Design",development:"Entwicklung",review:"Kundenprüfung",live:"Live",paused:"Pausiert",cancelled:"Abgebrochen"};

export default function PortalPage({params}:{params:Promise<{token:string}>}){
  const [token,setToken]=useState("");const [project,setProject]=useState<PortalProject|null>(null);const [error,setError]=useState("");const [kind,setKind]=useState<"text"|"link">("text");const [label,setLabel]=useState("");const [content,setContent]=useState("");const [sending,setSending]=useState(false);const [file,setFile]=useState<File|null>(null);const [fileLabel,setFileLabel]=useState("Datei");
  useEffect(()=>{void params.then(({token})=>{setToken(token);void load(token);});},[params]);
  async function load(t=token){const r=await fetch(`/api/portal/${t}`,{cache:"no-store"});const d=await r.json();if(!r.ok){setError(d.error||"Portal nicht verfügbar.");return;}setProject(d.project);setError("");}
  async function submit(){if(!label.trim()||!content.trim())return;setSending(true);const r=await fetch(`/api/portal/${token}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,label,content})});const d=await r.json();setSending(false);if(!r.ok){setError(d.error||"Speichern fehlgeschlagen.");return;}setLabel("");setContent("");await load();}
  async function upload(){if(!file)return;setSending(true);const form=new FormData();form.set("token",token);form.set("label",fileLabel||"Datei");form.set("file",file);const r=await fetch(portalUploadUrl,{method:"POST",body:form});const d=await r.json();setSending(false);if(!r.ok){setError(d.error||"Upload fehlgeschlagen.");return;}setFile(null);setFileLabel("Datei");await load();}
  if(error&&!project)return <main className="legal"><h1>Kundenportal</h1><p>{error}</p></main>;
  if(!project)return <main className="legal"><h1>Kundenportal</h1><p>Lädt …</p></main>;
  const received=[project.logo_received&&"Logo",project.images_received&&"Bilder",project.texts_received&&"Texte",project.domain_access_received&&"Domainzugang",project.legal_info_received&&"Rechtliche Angaben"].filter(Boolean);
  return <main className="legal" style={{maxWidth:1000}}><a className="brand" href="/"><span>W</span> WebForge</a><p style={{marginTop:30}}>KUNDENPORTAL · {project.project_number}</p><h1>{project.company}</h1><h2>{project.name}</h2><div className="stats" style={{marginTop:24}}><article><small>STATUS</small><strong>{statusLabels[project.status]||project.status}</strong></article><article><small>FORTSCHRITT</small><strong>{project.progress}%</strong></article><article><small>ZIELTERMIN</small><strong>{project.target_launch_date?new Date(project.target_launch_date).toLocaleDateString("de-DE"):"—"}</strong></article></div><div className="adminpanel"><h2>Was noch fehlt</h2><p>Bereits erhalten: {received.length?received.join(", "):"noch nichts markiert"}</p>{project.content_deadline&&<p>Content-Deadline: <strong>{new Date(project.content_deadline).toLocaleDateString("de-DE")}</strong></p>}{project.tasks.filter(t=>!t.completed).map(t=><div className="adminrow" key={t.id}><span className="dot"/><div><strong>{t.title}</strong><small>{t.notes||t.category}{t.due_date?` · fällig ${new Date(t.due_date).toLocaleDateString("de-DE")}`:""}</small></div><b>{t.required?"Pflicht":"Optional"}</b></div>)}</div><div className="adminpanel"><h2>Inhalte oder Links abgeben</h2><div style={{display:"grid",gap:10,maxWidth:680}}><select value={kind} onChange={e=>setKind(e.target.value as "text"|"link")}><option value="text">Text</option><option value="link">Link</option></select><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Bezeichnung, z. B. Über-uns-Text"/><textarea rows={5} value={content} onChange={e=>setContent(e.target.value)} placeholder={kind==="link"?"https://…":"Text eingeben …"}/><button className="button" onClick={()=>void submit()} disabled={sending}>Abgabe speichern</button></div></div><div className="adminpanel"><h2>Datei hochladen</h2><p>Erlaubt: JPG, PNG, WebP, SVG, PDF, TXT · maximal 10 MB.</p><div style={{display:"grid",gap:10,maxWidth:680}}><input value={fileLabel} onChange={e=>setFileLabel(e.target.value)} placeholder="Bezeichnung"/><input type="file" accept="image/jpeg,image/png,image/webp,image/svg+xml,application/pdf,text/plain" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="button" disabled={!file||sending} onClick={()=>void upload()}>Datei hochladen</button></div></div><div className="adminpanel"><h2>Deine bisherigen Abgaben</h2>{project.submissions.length===0?<p>Noch keine Abgaben.</p>:project.submissions.map(s=><div className="adminrow" key={s.id}><span className="dot"/><div><strong>{s.label}</strong><small>{s.kind==="file"?s.file_name:s.content}</small></div><small>{new Date(s.created_at).toLocaleString("de-DE")}</small></div>)}</div></main>;
}
